sudo: required
language: generic

services:
  - docker

before_install:
  # Build Docker image for testing:
  - echo Build client and api docker images for testing..
  - docker build -t loaymoh99/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t loaymoh99/nodejs-test -f ./api/Dockerfile.dev ./api

script:
  # Run tests with built Docker images:
  - echo Run react tests..
  - docker run -e CI=true loaymoh99/react-test
  - echo Run nodejs tests...
  - docker run -e CI=true loaymoh99/nodejs-test

after_success:
  - echo Building the production Docker image..
  - docker build -t loaymoh99/dkr-demo-client ./client
  - docker build -t loaymoh99/dkr-demo-nginx ./nginx
  - docker build -t loaymoh99/dkr-demo-api ./api
  # Log in to the docker CLI:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hubgit push -u origin main:
  - echo Pushing the Docker images..
  - docker push loaymoh99/dkr-demo-client
  - docker push loaymoh99/dkr-demo-nginx
  - docker push loaymoh99/dkr-demo-api

